### ISSUE TITLE
Eu denovo

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#285]
Sobre o esquema de deixa o antilinks mais eficiente...
 Agr ta dando esse erro:(node:5800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at isUrl (C:\Users\mathe\Desktop\iris-main\lib\functions.js:59:37)
    at C:\Users\mathe\Desktop\iris-main\index.js:45:43
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:5800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 28)

**Comment by KillovSky** [comment]
> Sobre o esquema de deixa o antilinks mais eficiente...
>  Agr ta dando esse erro:(node:5800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
>     at isUrl (C:\Users\mathe\Desktop\iris-main\lib\functions.js:59:37)
>     at C:\Users\mathe\Desktop\iris-main\index.js:45:43
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> (node:5800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 28)

Mostre-me como você inseriu o código na `index.js`.

E de segunda opção, insira o sistema de `Anti-Links` abaixo das `ifs` de mudar a linguagem na `config.js`.

Experimente também alocar mais RAM para a Íris.

Abra a `package.json` e procure por `node index.js`, mude para `--max-old-space-size=RAM`.

Troque a "RAM" pela quantidade de RAM que desejar em **megabytes**, quanto mais melhor, mas não esqueça de deixar um pouco pro PC não ser sobrecarregado.

Exemplo, se você tem 6GB RAM como eu, pode ser mais conveniente inserir 4096 em vez de 6144.

**Comment by MatheusOFC** [comment]
![IMG-20210923-WA1843](https://user-images.githubusercontent.com/77314121/134610668-a121b9ff-e8b5-4b4a-9283-ad65556bfccb.jpg)
![IMG-20210923-WA1844](https://user-images.githubusercontent.com/77314121/134610672-b4e08b57-aeb6-4224-8f1c-2fb303996187.jpg)


Aee os 2 ambos na índex como dito.

**Comment by MatheusOFC** [comment]
sobre o esquema da RAM, mudei mas o bot nem inicia

**Comment by KillovSky** [comment]
> ![IMG-20210923-WA1843](https://user-images.githubusercontent.com/77314121/134610668-a121b9ff-e8b5-4b4a-9283-ad65556bfccb.jpg)
> ![IMG-20210923-WA1844](https://user-images.githubusercontent.com/77314121/134610672-b4e08b57-aeb6-4224-8f1c-2fb303996187.jpg)
> 
> 
> Aee os 2 ambos na índex como dito.

Não ai, desfaça essa modificação, ela não possui relação com o "anti-links".

Pegue o sistema de anti-links da **config.js**, localizado na linha [253](https://github.com/KillovSky/iris/blob/main/config.js#L253) e insira ele na linha [198](https://github.com/KillovSky/iris/blob/main/config.js#L253), no espaço em branco.
Você tambem pode fazer uma funcão direta em ternary para inserir na linha [154](https://github.com/KillovSky/iris/blob/main/config.js#L154), está será mais rapida mas menos estavel.

```javascript
isGroupMsg && !isOwner && isUrl(chats) ? kill.removeParticipant(chatId, user) : false
```

Teoricamente isso deve te acelerar, sobre a Íris não iniciar, você provavelmente fez uma edição incorreta na package.json.

**Comment by MatheusOFC** [comment]
Desfaço as duas modificações que fiz em Index? Ou só a
 If (mensage.isGroupMsg.....

**Comment by MatheusOFC** [comment]
E pra fazer essas função direta só coloco 
isGroupMsg && !isOwner && isUrl(chats) ? kill.removeParticipant(chatId, user) : false

Na linha 154 na parte de parâmetros?

**Comment by KillovSky** [comment]
> E pra fazer essas função direta só coloco 
> isGroupMsg && !isOwner && isUrl(chats) ? kill.removeParticipant(chatId, user) : false
> 
> Na linha 154 na parte de parâmetros?
> 

Sim, insira na parametros, sobre desfazer as mudanças, simplesmente apague tudo que inseriu, se não sabe o que você mesmo inseriu, baixe novamente.
