### ISSUE TITLE
start erro

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#29]
TypeError: Cannot read property 'status' of null
    at Object.<anonymous> (C:\Users\Pichau\Downloads\iris-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:129:133)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Pichau\Downloads\iris-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

toda hora fica dando isso, ai eu resolvo ele inicia dps de 15 minutos ele cai

**Comment by KillovSky** [comment]
Obrigado por informar um erro por aqui na Github!
Tente com o novo update de agora e desculpe pelo inconveniente causado, aparentemente foi um erro na options.js, espero que consiga agora e se der erro novamente informe quando puder!
P.S: Mantenha os módulos atualizados com ```npm update```.
