### ISSUE TITLE
Patentes

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/iris#303]
Tais Patentes Adicionadas a íris, porém quando dou o start d tal erro

exemplo a seria o o nivel que o jogador se encontra? tipo a10= nivel 10?

> iris@3.1.1 start
> node index.js

internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Users\kotos\iris\lib\config\Gerais\patentes.json: Unexpected string in JSON at position 898
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\kotos\iris\lib\functions.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

As Patentes adicionadas foram as abaixos e mudando a colocação de I II III IV V em decrescente para os jogadores de moba:
{
	"a0": "Cobre",
	"a1": "Bronze V",
	"a2": "Bronze IV",
	"a3": "Bronze III",
	"a4": "Bronze II",
	"a5": "Bronze I",
	"a6": "Prata V",
	"a7": "Prata IV",
	"a8": "Prata III",
	"a9": "Prata II",
	"a10": "Prata I",
	"a11": "Ouro V",
	"a12": "Ouro IV",
	"a13": "Ouro III",
	"a14": "Ouro II",
	"a15": "Ouro I",
	"a16": "Diamante V",
	"a17": "Diamante IV",
	"a18": "Diamante III",
	"a19": "Diamante II",
	"a20": "Diamante I",
	"a100": "Diamante Mestre",
	"a150": "Aprendiz De Magia",
	"a200": "Mago Intermediario",
	"a350": "Arquimago",
	"a500": "Mago Anciao",
	"a600": "Sábio",
	"a700": "Elite",
	"a800": "Global",
	"a950": "Heroi",
	"a1200": "Anti-Heroi",
	"a1500": "Lendario",
	"a2500": "Semi-Deus",
	"a3500": "Arcanjo",
	"a4500": "Demoniaco",
	"a4600": "Bardo",
	"a4700": "Druida",
	"a4800": "Paladino",
	"a4900": "Bruxo Medieval",
	"a7000": "Divindade II"
	"a10000": "Divindade I",

}

**Comment by Bisgos** [comment]
Tira a vírgula no final de Divindade I e coloca no Divindade II e seja Feliz!
ficando assim:
"a7000": "Divindade II",
"a10000": "Divindade I"
