### ISSUE TITLE
Bot nao responde alguns comandos em grupo

### ISSUE THREAD

**Issue by xinarai123** [KillovSky/iris#328]
alguns comandos como /nivel, /welcome e outros o bot fica apenas digitando e da esse erro no prompt:

(node:6312) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at Object.window.<computed>.<computed> [as getNewMessageId] (__puppeteer_evaluation_script__:1:209239)
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:203845)
    at ExecutionContext._evaluateInternal (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(node:6312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)

**Comment by EndervorHero** [comment]
Same here! D:

**Comment by xinarai123** [comment]
> Mesmo aqui! D:

try to update your google chorome, I think it worked in mine, if it does, let me know so I can close the issue. ( no meu resolveu so atualizei o chorome...)

**Comment by KillovSky** [comment]
Aparentemente é um erro da wa-automate em adquirir novas mensagens, reiniciar deve resolver.
Além disso, apague a pasta `logs` antes de abrir.
