### ISSUE TITLE
error iris

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#341]
(node:4668) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:200982)
    at ExecutionContext._evaluateInternal (C:\Users\Born4Kill\Desktop\BT-LIMONCIO\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\Born4Kill\Desktop\BT-LIMONCIO\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PedroBatistop** [comment]
#331

**Comment by marru453** [comment]
@PedroBatistop vale esperare hasta mañana y probare por si funciona, tenía todo actualizado, node, npm update y me sigue dando el mismo error, pero al leer el #331 esperare. este error se debe a la caida de servidor de whatsapp?
