### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#36]
> iris@3.0.14 start
> node index.js

undefined:1

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\Pichau\Downloads\iris-main\config.js:94:23)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\Pichau\Downloads\iris-main\index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)

já baixei, ja desinstalei, ja troquei arquivo, ja tentei executar seu bot por git clone, e nada funciona, tudo que tentei fica dando esse crash (isso aí é de npm start, com node index.js ele dá mais erros)

**Comment by KillovSky** [comment]
A linha [94](https://github.com/KillovSky/iris/blob/main/config.js#L94) faz referência ao arquivo `msgcount.json`, responsável por contar mensagens, acredito que este arquivo possa estar corrompido por um desligamento inesperado da BOT, use um dos backups automáticos para tentar iniciar, aguardo por notícias.

**Comment by lonnykkkj** [comment]
como eu faço um backup? ou uso eles? só renomear o arquivo?

**Comment by lonnykkkj** [comment]
já consegui fazer, e funcionou, valeu de verdade irmão, isso aconteceu pq eu reiniciei meu pc com o bot aberto kkkk, nao sabia dessa de fechar inesperadamente, mas agora vou fechar o bot antes de desligar meu pc irmão, valeu

**Comment by KillovSky** [comment]
Que ótimo que funcionou, sinta-se a vontade para abrir outra issue quando quiser e bom uso da Íris!
