### ISSUE TITLE
erro e fecha a iris

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#411]
![image](https://user-images.githubusercontent.com/65947059/144929597-8797af8d-66fa-4ae9-95d3-b3116b59bf6a.png)

**Comment by pablorere** [comment]
Error: ENOENT, No such file or directory 'ERROR: 401'
    at setSource (C:\Users\silver tape\Pictures\iris-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\silver tape\Pictures\iris-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\silver tape\Pictures\iris-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (C:\Users\silver tape\Pictures\iris-main\node_modules\canvas\index.js:23:10)
    at Rank.build (C:\Users\silver tape\Pictures\iris-main\node_modules\canvacord\src\Rank.js:477:35)
    at kconfig (C:\Users\silver tape\Pictures\iris-main\config.js:2705:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\silver tape\Pictures\iris-main\index.js:46:3 {
  errno: 2,
  code: 'ENOENT',
  path: 'ERROR: 401',
  syscall: 'fopen'
}

**Comment by KillovSky** [comment]
#107
