### ISSUE TITLE
outro erro do wellcome eu concertei com o 401 e aparece esse agr

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#413]
C:\Users\silver tape\Pictures\iris-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: Error: Unexpected null or undefined: this.quotedParticipant
    at t.default (https://web.whatsapp.com/:2:287)
    at Object._getQuotedMsgObj (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:56:415188)
    at Object.quotedMsgObj (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:56:414705)
    at __puppeteer_evaluation_script__:1:208783
    at Array.filter (<anonymous>)
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:208472)
    at ExecutionContext._evaluateInternal (C:\Users\silver tape\Pictures\iris-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\silver tape\Pictures\iris-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by KillovSky** [comment]
#412 | Duplicate
