### ISSUE TITLE
erro ao tentar ler qr code com WhatsApp multi dispositivos ativado

### ISSUE THREAD

**Issue by xinarai123** [KillovSky/iris#414]
- Multi-Device detected, please set multiDevice to true in your config or add the --multi-device flag
- Starting
- Version: 4.25.1
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove themm
- Launching Browser
- Setting Up Page
- Loading session data
- No session data file found for session : Iris
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Navigating to WA
- Page loaded but something may have gone wrong: 1562ms
- Browser Launched
- Please delete the ./logs/Chrome folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:513:34)
    at DOMWorld.waitForFunction (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:468:26)
    at Frame.waitForFunction (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:909:32)
    at Page.waitForFunction (C:\Users\gabri\iris\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2433:33)
    at C:\Users\gabri\iris\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:194:26
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\gabri\iris\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by KillovSky** [comment]
#415

**Comment by EmanuelPeixoto** [comment]
se não puder, desculpe, mas abriram uma issue no wa-automate sobre, isso não é problema na iris em si, é no wa-automate ao injetar no chromium https://github.com/open-wa/wa-automate-nodejs/issues/2346
