### ISSUE TITLE
error comando level

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#452]
C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'ERROR: 401'
    at setSource (C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvas\index.js:23:10)
    at Rank.build (C:\Users\Marru\Desktop\BT-LIMONCIO\node_modules\canvacord\src\Rank.js:477:35)
    at kconfig (C:\Users\Marru\Desktop\BT-LIMONCIO\config.js:3836:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Marru\Desktop\BT-LIMONCIO\index.js:46:3 {
  errno: 2,
  code: 'ENOENT',
  path: 'ERROR: 401',
  syscall: 'fopen'
}

**Comment by KillovSky** [comment]
Prueba la [Release 3.2.5](https://github.com/KillovSky/iris/commit/b742993aacd35ad06d7b1427e395becf43182923).

**Comment by marru453** [comment]
Pero esa versión funciona bien el idioma en español? Ya que mi bot está en idioma es.js. mañana lo voy a probar y si veo algunos Bugs lo diré

**Comment by KillovSky** [comment]
> @KillovSky 
> Pero esa versión funciona bien el idioma en español? Ya que mi bot está en idioma es.js. mañana lo voy a probar y si veo algunos Bugs lo diré, hay un bug no he visto a nadie que lo haya dicho que el bot si queda congelado o se crashea a veces

No use `en` o `es`, son inestables y con errores, usa el portugués por ahora, hasta que hable sobre la estabilidad del idioma.

**Comment by marru453** [comment]
De acuerdo, lo editaré y lo pasaré a un idioma español mientras que el código lo dejaré en idioma portugués. Ya en cuanto haya estabilidad dejaré el de portugués como estaba y usaré el de es.
