### ISSUE TITLE
erro welcome ( IRIS DEV)

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#476]
BOT NAO DA BOAS VINDAS NEM ADEUS, NO TERMINAL APARECE ISSO: 
[ENTROU] Biel - (556282******) entrou no grupo ⚡𝐾𝐿 𝑆𝐻𝐼𝑇𝑆⚡...
Error: Server responded with 404
    at C:\Users\gabri\alfred\node_modules\canvas\lib\image.js:56:28
    at C:\Users\gabri\alfred\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (C:\Users\gabri\alfred\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (events.js:519:28)
    at PassThrough.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by KillovSky** [comment]
Tente instalar a [Versão 3.2.6](https://github.com/KillovSky/iris/tree/dev) e divirta-se!
Não esqueça de ler a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8).
