### ISSUE TITLE
BUG -> Profile [Multiple-Devices • WA-BETA]

### ISSUE THREAD

**Issue by ruanpablodev** [KillovSky/iris#489]
ola lucas, estou tendo erro no comando perfil, segue os dados informados:

**Erro no Console:**

 COMANDO "[/PERFIL]" AS 11/01/22 11:18:41 DE "DKZ HYPADO - [553172271466]" EM "ʀᴇᴠᴇɴɢᴇʀs ᴇʟɪᴛᴇ ᴏғᴄ👾|ﾚｱｲﾒ"
[FALHA GERAL] Error: Evaluation failed: TypeError: e.isUser is not a function
    at https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152413
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:64054
    at x (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:408838)
    at new g (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:404398)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63935
    at t.default (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152260)
    at t.getStatus (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:42:125454)
    at ExecutionContext._evaluateInternal (C:\Users\Alexa\desktop\iris-dev2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\Alexa\desktop\iris-dev2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    
    **Mensagem enviada pelo bot:**
    

😵 Ooops, algo de errado aconteceu comigo, de uma olhada nos detalhes abaixo e se puder envie isso ao meu host [wa.me/553172271466] ou use o /help!

#️⃣  - "/perfil"

❓- "Error"

❌ - "Evaluation failed: TypeError: e.isUser is not a function
    at https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152413
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:64054
    at x (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:408838)
    at new g (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:2:404398)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.28b6b8e610a5c3159208.js:2:63935
    at t.default (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:3:152260)
    at t.getStatus (https://web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js:42:125454)"

📅 - "11/01/22 11:18:41"

❗ - "Erro não detalhado, descrição acima."

📁 - "    at https"

🧶 - "Linha #//web.whatsapp.com/bootstrap_qr.463c81833344582ab256.js

🔍 - "Caractere #3"

**Comment by KillovSky** [comment]
Erro referente ao `Multi-Devices`, ainda preciso fazer uma implementação para evitar bugs assim, portanto, espere por atualizações, até lá, tem duas opções:

. - Remover os parametros com defeito você mesmo.
. - Usar o WhatsApp sem Multi-Device

**Comment by KillovSky** [comment]
Erro referente ao `Multi-Devices`, ainda preciso fazer uma implementação para evitar bugs assim, portanto, espere por atualizações, até lá, tem duas opções:

- Remover os parametros com defeito você mesmo.
- Usar o WhatsApp sem Multi-Device

**Comment by maradona4** [comment]
![Screenshot_20220320-013525_WhatsAppBusiness](https://user-images.githubusercontent.com/44541791/159148402-a0b2f656-43dd-4693-8058-f20dd5a9c1f2.jpg)

Não tô achando sair beta Múltiplos, você tem alguma sugestão de como sair ou voltar pra atualização recente?

**Comment by KillovSky** [comment]
> ![Screenshot_20220320-013525_WhatsAppBusiness](https://user-images.githubusercontent.com/44541791/159148402-a0b2f656-43dd-4693-8058-f20dd5a9c1f2.jpg)
> 
> Não tô achando sair beta Múltiplos, você tem alguma sugestão de como sair ou voltar pra atualização recente? 

Não é mais função Beta, foi integrada totalmente no WhatsApp, você deve usar o `Multiple Devices` agora.
