### ISSUE TITLE
nao consigo iniciar 

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#512]
![image](https://user-images.githubusercontent.com/65947059/151640993-0fdc383d-d77e-434a-8217-6abccc9cb32a.png)

npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15, @spence-s, and @niftylettuce. Superagent is sponsored by Forward Email at <https://forwardemail.net>.
npm ERR! code 1
npm ERR! path C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find version of `python`
npm ERR!     at binaryVersion (file:///C:/Users/pablo_zm6jmq2/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/pablo_zm6jmq2/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pablo_zm6jmq2\AppData\Local\npm-cache\_logs\2022-01-29T01_05_44_879Z-debug.log

C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev>npm start

> iris@3.2.6 start
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\index.js:4:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pablo_zm6jmq2\\Documents\\iris-dev_2\\iris-dev\\index.js'
  ]
}

C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev>

**Comment by pablorere** [comment]
> ![image](https://user-images.githubusercontent.com/65947059/151640993-0fdc383d-d77e-434a-8217-6abccc9cb32a.png)
> 
> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see [request/request#3142](https://github.com/request/request/issues/3142) npm WARN deprecated har-validator@5.1.5: this library is no longer supported npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142) npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent. We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing. See the releases tab for more information at https://github.com/visionmedia/superagent/releases. Thanks to @shadowgate15, @Spence-S, and @niftylettuce. Superagent is sponsored by Forward Email at https://forwardemail.net. npm ERR! code 1 npm ERR! path C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\node_modules\youtube-dl-exec npm ERR! command failed npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2" npm ERR! Error: Couldn't find version of `python` npm ERR! at binaryVersion (file:///C:/Users/pablo_zm6jmq2/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8) npm ERR! at processTicksAndRejections (node:internal/process/task_queues:96:5) npm ERR! at async binaryVersionCheck (file:///C:/Users/pablo_zm6jmq2/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\pablo_zm6jmq2\AppData\Local\npm-cache_logs\2022-01-29T01_05_44_879Z-debug.log
> 
> C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev>npm start
> 
> > iris@3.2.6 start
> > node index.js
> 
> node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module '@open-wa/wa-automate' Require stack:
> 
> * C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\index.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\index.js:4:5)
>   at Module._compile (node:internal/modules/cjs/loader:1101:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev\index.js'
>   ]
>   }
> 
> C:\Users\pablo_zm6jmq2\Documents\iris-dev_2\iris-dev>
