### ISSUE TITLE
Falha ao Iniciar - Error: Cannot find module

### ISSUE THREAD

**Issue by DinhoNunesLC** [KillovSky/iris#569]
root@vps38741:~/iris# npm start

> iris@3.1.1 start /root/iris
> node index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/iris/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iris@3.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iris@3.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-24T19_55_51_655Z-debug.log
root@vps38741:~/iris#

**Comment by KillovSky** [comment]
Apague a pasta da Íris e instale a `Branch DEV`.

#431 <- Solução para o mesmo BUG

#416 <- Versão mais atualizada da Íris

A solução exige reinstalação, portanto, use a `DEV`, ela é superior em tudo, exceto no quesito de múltiplos idiomas.
