### ISSUE TITLE
erro ao dar algum comando, crash

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/Iris#605]
START - OK] A sessão foi iniciada, carregando módulos e arquivos...você poderá usar em alguns instantes!

-------------------------------

TypeError: Cannot read property 'kconfig' of undefined
    at C:\Users\kotos\iris\lib\functions\controller.js:198:21
    at Client.<anonymous> (C:\Users\kotos\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\kotos\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:28:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Unhandled Rejection at Promise Promise {
  <rejected> TypeError: Cannot read property 'kconfig' of undefined
      at C:\Users\kotos\iris\lib\functions\controller.js:198:21
      at Client.<anonymous> (C:\Users\kotos\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:92)
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\kotos\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:28:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by KillovSky** [comment]
https://github.com/KillovSky/Iris/issues/604

Vá na pasta `functions` e insira o seguinte arquivo, substitua por cima mesmo, tente iniciar e poste o erro que enviar, mas tenho quase total certeza que isso é má instalação.

[Debugging index.js](https://cdn.discordapp.com/attachments/1000564568944287815/1074423672837775381/index.js)

**Comment by Nhamin** [comment]
[START - OK] A sessão foi iniciada, carregando módulos e arquivos...você poderá usar em alguns instantes!

-------------------------------

Tool não encontrada ou erro, detalhes abaixo!

 C:\Users\kotos\OneDrive\Área de Trabalho\iris\lib\functions\config.js:257
                if (message.body == '/debugping') return await kill.reply(message.from, `DEBUG: ${procTime} segundos`, message.id);
                                                         ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at tools (C:\Users\kotos\OneDrive\Área de Trabalho\iris\lib\functions\index.js:4:25)
    at C:\Users\kotos\OneDrive\Área de Trabalho\iris\lib\functions\controller.js:198:6
    at Client.<anonymous> (C:\Users\kotos\OneDrive\Área de Trabalho\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:92)
TypeError: Cannot read property 'kconfig' of undefined
    at C:\Users\kotos\OneDrive\Área de Trabalho\iris\lib\functions\controller.js:198:21
    at Client.<anonymous> (C:\Users\kotos\OneDrive\Área de Trabalho\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\kotos\OneDrive\Área de Trabalho\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:28:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Unhandled Rejection at Promise Promise {
  <rejected> TypeError: Cannot read property 'kconfig' of undefined
      at C:\Users\kotos\OneDrive\Área de Trabalho\iris\lib\functions\controller.js:198:21
      at Client.<anonymous> (C:\Users\kotos\OneDrive\Área de Trabalho\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:92)
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\kotos\OneDrive\Área de Trabalho\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:28:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by KillovSky** [comment]
Desfaça qualquer edição feita ou retire o await, no entanto, esse erro não é normal, pois existe definição do async e essa função sempre é executada bem em quaisquer versão, logo, houve má alteração, corrupção (o arquivo continua legível, portanto não é isso) ou sua versão do nodejs é muito antiga e não suporta async (erro diz sobre async, então não é isso), não há outras formas deste erro ocorrer.
